/* eslint-disable no-inline-comments */
module.exports = {
	// Command aliases
	aliasCommands: {
		addcredits: "addcredit",
		bal: "balance",
		bc: "broadcast",
		bl: "blacklist",
		cmds: "help",
		commands: "help",
		contact: "contacts",
		exchange: "convert",
		credits: "balance",
		delstrike: "rmstrike",
		discoin: "convert",
		ho: "handover",
		id: "identify",
		invite: "links",
		link: "links",
		mentions: "mention",
		msg: "message",
		pc: "permcheck",
		perm: "permcheck",
		promo: "promote",
		rates: "convert",
		suggest: "links",
		unassign: "deassign",
		upvote: "links",
		vote: "links",
		wl: "whitelist",
	},
};
