export const aliases = {
	addcredits: "addcredit",
	bal: "balance",
	bc: "broadcast",
	bl: "blacklist",
	cmds: "help",
	commands: "help",
	contact: "contacts",
	exchange: "convert",
	credits: "balance",
	delstrike: "rmstrike",
	id: "identify",
	invite: "links",
	link: "links",
	mentions: "mention",
	msg: "message",
	pc: "permcheck",
	perm: "permcheck",
	promo: "promote",
	unassign: "deassign",
	vote: "links",
	wl: "whitelist"
}